"""initial schema

Revision ID: f88029c9ba16
Revises: 
Create Date: 2026-03-19 01:47:45.995782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f88029c9ba16'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clustering_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('algorithm', sa.String(), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('asof_date', sa.Date(), nullable=False),
    sa.Column('window_days', sa.Integer(), nullable=False),
    sa.Column('n_clusters', sa.Integer(), nullable=True),
    sa.Column('silhouette', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_clustering_runs_asof', 'clustering_runs', ['asof_date'], unique=False)
    op.create_index('idx_clustering_runs_created', 'clustering_runs', ['created_at'], unique=False)
    op.create_table('daily_quotes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('high', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('low', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('close', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('adj_factor', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('high >= low AND open >= 0 AND close >= 0', name='chk_ohlc'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'trade_date', name='uq_daily_quotes_stock_date')
    )
    op.create_index('idx_daily_quotes_date', 'daily_quotes', ['trade_date'], unique=False)
    op.create_index('idx_daily_quotes_stock_date', 'daily_quotes', ['stock_id', 'trade_date'], unique=False)
    op.create_index(op.f('ix_daily_quotes_stock_id'), 'daily_quotes', ['stock_id'], unique=False)
    op.create_table('stock_features',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('asof_date', sa.Date(), nullable=False),
    sa.Column('window_days', sa.Integer(), nullable=False),
    sa.Column('total_return', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('return_percentile', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('annual_volatility', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('max_drawdown', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('downside_vol', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('trend_slope', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('trend_r2', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('ma_bullish', sa.Boolean(), nullable=True),
    sa.Column('trend_reversals', sa.Integer(), nullable=True),
    sa.Column('avg_volume', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('volume_volatility', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'asof_date', 'window_days', name='uq_stock_features_key')
    )
    op.create_index('idx_stock_features_stock_date', 'stock_features', ['stock_id', 'asof_date'], unique=False)
    op.create_index('idx_stock_features_window', 'stock_features', ['asof_date', 'window_days'], unique=False)
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exchange', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('list_date', sa.Date(), nullable=True),
    sa.Column('csrc_code', sa.String(), nullable=True),
    sa.Column('csrc_desc', sa.String(), nullable=True),
    sa.Column('province', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('asof', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("exchange IN ('Shanghai_Stocks', 'Shenzen_Stocks', 'Beijing_Stocks')", name='chk_exchange'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exchange', 'symbol', name='uq_stocks_exchange_symbol')
    )
    op.create_index('idx_stocks_asof', 'stocks', ['asof'], unique=False)
    op.create_index('idx_stocks_category', 'stocks', ['exchange', 'category'], unique=False)
    op.create_index('idx_stocks_exchange', 'stocks', ['exchange'], unique=False)
    op.create_index('idx_stocks_symbol', 'stocks', ['symbol'], unique=False)
    op.create_table('stocks_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exchange', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('list_date', sa.Date(), nullable=True),
    sa.Column('csrc_code', sa.String(), nullable=True),
    sa.Column('csrc_desc', sa.String(), nullable=True),
    sa.Column('province', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('asof', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_stocks_history_asof', 'stocks_history', ['asof'], unique=False)
    op.create_index('idx_stocks_history_key', 'stocks_history', ['exchange', 'symbol', 'asof'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'running', 'completed', 'failed', 'cancelled')", name='chk_task_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tasks_created', 'tasks', ['created_at'], unique=False)
    op.create_index('idx_tasks_status', 'tasks', ['status'], unique=False)
    op.create_index('idx_tasks_type', 'tasks', ['type'], unique=False)
    op.create_table('cluster_explanations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('cluster_label', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('input_summary', sa.Text(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('disclaimer', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['clustering_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'cluster_label', name='uq_cluster_explanation')
    )
    op.create_index('idx_cluster_explanations_run', 'cluster_explanations', ['run_id'], unique=False)
    op.create_table('clustering_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('cluster_label', sa.Integer(), nullable=False),
    sa.Column('distance', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['clustering_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'stock_id', name='uq_clustering_members')
    )
    op.create_index('idx_clustering_members_label', 'clustering_members', ['run_id', 'cluster_label'], unique=False)
    op.create_index('idx_clustering_members_run', 'clustering_members', ['run_id'], unique=False)
    op.create_index('idx_clustering_members_stock', 'clustering_members', ['stock_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_clustering_members_stock', table_name='clustering_members')
    op.drop_index('idx_clustering_members_run', table_name='clustering_members')
    op.drop_index('idx_clustering_members_label', table_name='clustering_members')
    op.drop_table('clustering_members')
    op.drop_index('idx_cluster_explanations_run', table_name='cluster_explanations')
    op.drop_table('cluster_explanations')
    op.drop_index('idx_tasks_type', table_name='tasks')
    op.drop_index('idx_tasks_status', table_name='tasks')
    op.drop_index('idx_tasks_created', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index('idx_stocks_history_key', table_name='stocks_history')
    op.drop_index('idx_stocks_history_asof', table_name='stocks_history')
    op.drop_table('stocks_history')
    op.drop_index('idx_stocks_symbol', table_name='stocks')
    op.drop_index('idx_stocks_exchange', table_name='stocks')
    op.drop_index('idx_stocks_category', table_name='stocks')
    op.drop_index('idx_stocks_asof', table_name='stocks')
    op.drop_table('stocks')
    op.drop_index('idx_stock_features_window', table_name='stock_features')
    op.drop_index('idx_stock_features_stock_date', table_name='stock_features')
    op.drop_table('stock_features')
    op.drop_index(op.f('ix_daily_quotes_stock_id'), table_name='daily_quotes')
    op.drop_index('idx_daily_quotes_stock_date', table_name='daily_quotes')
    op.drop_index('idx_daily_quotes_date', table_name='daily_quotes')
    op.drop_table('daily_quotes')
    op.drop_index('idx_clustering_runs_created', table_name='clustering_runs')
    op.drop_index('idx_clustering_runs_asof', table_name='clustering_runs')
    op.drop_table('clustering_runs')
    # ### end Alembic commands ###
